# Generated by Django 5.1.1 on 2024-09-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Woah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.TextField(default='', max_length=40)),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')])),
                ('SID', models.IntegerField(blank=True, default='', primary_key=True, serialize=False, unique=True)),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BNS', 'Business'), ('MED', 'Medicene'), ('COM', 'Communication'), ('ART', 'Art & Design')], max_length=40)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=40)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('course', models.OneToOneField(max_length=60, on_delete=django.db.models.deletion.PROTECT, to='college2.woah')),
            ],
        ),
    ]
