# Generated by Django 5.1.1 on 2024-09-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Woah',
            new_name='Course',
        ),
    ]
