# Generated by Django 5.1.1 on 2024-09-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college2', '0003_course_video_expire_course_video_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SID',
            field=models.IntegerField(blank=True, default='', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
