# Generated by Django 5.1.1 on 2024-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college2', '0004_alter_student_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BNS', 'Business'), ('MED', 'Medicene'), ('COM', 'Communication'), ('ART', 'Art & Design')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], max_length=50, null=True),
        ),
    ]
