# Generated by Django 5.1.1 on 2024-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college2', '0005_course_course_major_course_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.CharField(choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[]),
        ),
    ]
